spring.application.name=SmartQueueManagement
spring.datasource.url=jjdbc:mysql://acela.proxy.rlwy.net:23547/smart_queue_management
spring.datasource.username=root
spring.datasource.password= noTgkIwwLmUVctWvfqEYWlhiJIxZCYlH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true